{"name": "Регистрация существующего курьера", "status": "passed", "description": "Проверяем ожидаемую ошибку, удаляем курьера", "start": 1713785028777, "stop": 1713785029558, "uuid": "7f111852-11f6-4b35-8933-86eff233ef10", "historyId": "cf269a25aa8f451cb51d06fe26b80fd6", "testCaseId": "cf269a25aa8f451cb51d06fe26b80fd6", "fullName": "tests.test_create_courier.TestCreateCourier#test_registration_double_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "debian"}, {"name": "thread", "value": "18476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}