{"name": "Регистрация существующего курьера", "status": "passed", "description": "Проверяем ожидаемую ошибку, удаляем курьера", "start": 1713788786907, "stop": 1713788787730, "uuid": "f7cdf601-d4a2-4574-945e-d60aac9f3bd1", "historyId": "cf269a25aa8f451cb51d06fe26b80fd6", "testCaseId": "cf269a25aa8f451cb51d06fe26b80fd6", "fullName": "tests.test_create_courier.TestCreateCourier#test_registration_double_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "debian"}, {"name": "thread", "value": "19783-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}